### ISSUE TITLE
If auth fails, client doesn't offer useful error info

### ISSUE THREAD

**Issue by ericandrewlewis** [baalexander/node-xmlrpc#121]
This is a great library :smile: thank you for it.

If I give the wrong credentials for basic auth to the client, I don't get back a useful error message. The error I get in my callback is `[Error: Unknown XML-RPC tag 'TITLE']`, which I guess is because a 401 page back from the webserver which [can't be handled by the deserializer](https://github.com/baalexander/node-xmlrpc/blob/master/lib/client.js#L126).

Would it be possible to check for a 401, and give this info to the callback?

Here's my sample code

```js
var xmlrpc = require('xmlrpc')

var client = xmlrpc.createSecureClient({
	hostname: 'example.com',
	port: 443,
	path: '/login/xmlrpc',
	basic_auth: {
		user: 'eric',
		pass: 'password'
	}
})
client.methodCall(
	'ticket.putAttachment',
	[
		1,
		'1.diff',
		'',
		new Buffer( new Buffer('glerf').toString('base64'), 'base64'),
		false
	], function( err, value ) {
		if ( err === null ) {
			grunt.log.write( 'Uploaded patch.' )
			process.exit()
		} else {
			// Something went wrong, maybe auth, maybe something else
			console.log( err )
			process.exit(1)
		}
	}
)
```

**Comment by patricklodder** [comment]
We have enriched the error that was returned client-side with some additional information, please see https://github.com/baalexander/node-xmlrpc#to-debug-client-side for some documentation on how to fetch the response status.
