### ISSUE TITLE
Better error handling for invalid response

### ISSUE THREAD

**Issue by jzaefferer** [baalexander/node-xmlrpc#61]
The xml-rpc API in WordPress produces invalid responses (usually a html error page) under certain error conditions. In those cases, access to the actual response would be very valuable to debug the issue. Currently all we get is something like `Unknown XML-RPC tag 'TITLE'`.

Would be used in https://github.com/scottgonzalez/node-wordpress and https://github.com/scottgonzalez/grunt-wordpress

**Comment by ibrahim-bouncoula** [comment]
LOL
