### ISSUE TITLE
encodeIso8601 produces odd results with wordpress when acting as a client

### ISSUE THREAD

**Issue by stockholmux** [baalexander/node-xmlrpc#77]
The function encodeIso8601 in date_formatter.js produces odd results when trying to act as an XML RCP client for wordpress. Wordpress expects the dates to end in a Z or the have the GMT offset. Since encodeIso8601 just leaves the ends with  `+ zeroPad(date.getSeconds(), 2)` it breaks. In my project I have changed encodeIso8601 to include the ` + 'Z'` but perhaps there is a way to provide an override to the encodeIso8601 or take into account the GMT offset.

**Comment by patricklodder** [comment]
This has been fixed in 1.3.0
