### ISSUE TITLE
HTTPS support?

### ISSUE THREAD

**Issue by dpacmittal** [baalexander/node-xmlrpc#97]
I am trying to speak to an XMLRPC server over port 443, but it throws a 400 bad request error. Here's the response dump:

    res code: 400
    res body: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
    <html><head>
    <title>400 Bad Request</title>
    </head><body>
    <h1>Bad Request</h1>
    <p>Your browser sent a request that this server could not understand.<br />
    Reason: You're speaking plain HTTP to an SSL-enabled server port.<br />
     Instead use the HTTPS scheme to access this URL, please.<br />
    </p>
    <hr>
    <address>Apache/2.4.7 (Ubuntu) Server at 127.0.1.1 Port 443</address>
    </body></html>

**Comment by patricklodder** [comment]
You can use: ```var client = xmlrpc.createSecureClient(your_options);``` to get a https client.
